Numerous small bug fixes + time_since_start() definition. Among other things * add nCount to MSEPInfo.  Though maybe I should just use length msep. * Types in function signatures must be defined before use * maximum, not max, is the right thing to use for vectors * :: not : for types * expansion not  expension * missing subscripts * define push! in Base to avoid later assumption it only refers to my module * avoid computing remaining time or iterations until we have enough of a sample
All of which is enough to get me to here, a problem with my attempted
use of Iterators.product() and/or generator syntax in
         remainingIterations3 = sum(remaining_iterations(si, islice...) for
            islice in Iterators.product(ipos->axes(si.msep, ipos) for i in 1:3))

PS C:\Users\rdboylan\Documents\BP\MSEP\src> julia -t3 --project -- bigsim4.jl
isDone(1, 1, 1)
isDone(1, 1, 1)
isDone(1, 1, 2)
isDone(1, 2, 1)
isDone(1, 2, 2)
isDone(2, 1, 1)
isDone(2, 1, 2)
isDone(2, 2, 1)
isDone(2, 2, 2)
To iteration 1 total time so far 0.11183333333333334.
isDone(1, 1, 1)
isDone(1, 1, 1)
isDone(1, 1, 2)
isDone(1, 2, 1)
isDone(1, 2, 2)
isDone(2, 1, 1)
isDone(2, 1, 2)
isDone(2, 2, 1)
isDone(2, 2, 2)
To iteration 2 total time so far 0.15518333333333334.
isDone(1, 1, 1)
isDone(1, 1, 1)
isDone(1, 1, 2)
isDone(1, 2, 1)
isDone(1, 2, 2)
isDone(2, 1, 1)
isDone(2, 1, 2)
isDone(2, 2, 1)
isDone(2, 2, 2)
isDone(1, 1, 1)
isDone(1, 1, 1)
isDone(2, 1, 1)
isDone(2, 1, 1)
isDone(1, 2, 1)
isDone(1, 2, 1)
isDone(2, 2, 1)
isDone(2, 2, 1)
isDone(1, 1, 2)
isDone(1, 1, 2)
isDone(2, 1, 2)
isDone(2, 1, 2)
isDone(1, 2, 2)
isDone(1, 2, 2)
isDone(2, 2, 2)
isDone(2, 2, 2)
isDone(1, 1, 1)
isDone(2, 1, 1)
isDone(1, 2, 1)
isDone(2, 2, 1)
isDone(1, 1, 2)
isDone(2, 1, 2)
isDone(1, 2, 2)
isDone(2, 2, 2)
ERROR: LoadError: MethodError: no method matching remaining_iterations(::SimInfo, ::var"#34#40"{SimInfo})
Closest candidates are:
  remaining_iterations(::SimInfo, ::Any, ::Any, ::Any) at C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:498
  remaining_iterations(::SimInfo, ::Any, ::Any, ::Any, ::Any) at C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:471
  remaining_iterations(::SimInfo) at C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:559
Stacktrace:
  [1] (::var"#32#38"{SimInfo})(islice::Tuple{var"#34#40"{SimInfo}})
    @ Main .\none:0
  [2] MappingRF
    @ .\reduce.jl:95 [inlined]
  [3] _foldl_impl
    @ .\reduce.jl:58 [inlined]
  [4] foldl_impl(op::Base.MappingRF{var"#32#38"{SimInfo}, Base.BottomRF{typeof(Base.add_sum)}}, nt::Base._InitialValue, itr::Base.Iterators.ProductIterator{Tuple{Base.Generator{UnitRange{Int64}, var"#33#39"{SimInfo}}}})
    @ Base .\reduce.jl:48
  [5] mapfoldl_impl(f::typeof(identity), op::typeof(Base.add_sum), nt::Base._InitialValue, itr::Base.Generator{Base.Iterators.ProductIterator{Tuple{Base.Generator{UnitRange{Int64}, var"#33#39"{SimInfo}}}}, var"#32#38"{SimInfo}})
    @ Base .\reduce.jl:44
  [6] mapfoldl(f::Function, op::Function, itr::Base.Generator{Base.Iterators.ProductIterator{Tuple{Base.Generator{UnitRange{Int64}, var"#33#39"{SimInfo}}}}, var"#32#38"{SimInfo}}; init::Base._InitialValue)
    @ Base .\reduce.jl:170
  [7] mapfoldl
    @ .\reduce.jl:170 [inlined]
  [8] #mapreduce#263
    @ .\reduce.jl:302 [inlined]
  [9] mapreduce
    @ .\reduce.jl:302 [inlined]
 [10] #sum#266
    @ .\reduce.jl:528 [inlined]
 [11] sum(f::Function, a::Base.Generator{Base.Iterators.ProductIterator{Tuple{Base.Generator{UnitRange{Int64}, var"#33#39"{SimInfo}}}}, var"#32#38"{SimInfo}})
    @ Base .\reduce.jl:528
 [12] sum(a::Base.Generator{Base.Iterators.ProductIterator{Tuple{Base.Generator{UnitRange{Int64}, var"#33#39"{SimInfo}}}}, var"#32#38"{SimInfo}}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base .\reduce.jl:557
 [13] sum(a::Base.Generator{Base.Iterators.ProductIterator{Tuple{Base.Generator{UnitRange{Int64}, var"#33#39"{SimInfo}}}}, var"#32#38"{SimInfo}})
    @ Base .\reduce.jl:557
 [14] report(io::Base.TTY, si::SimInfo, outer_iter::Int64)
    @ Main C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:615
 [15] big4sim(evr::EVRequests; μs::Vector{Float64}, σs::Vector{Float64}, τs::Vector{Float64}, clusterSizes::Vector{Int64}, maxsd::Float64)
    @ Main C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:683
 [16] top-level scope
    @ C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:699
in expression starting at C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:699
PS C:\Users\rdboylan\Documents\BP\MSEP\src>