BANG.  Slight changes inside outer() cause failure:
PS C:\Users\rdboylan\Documents\BP\MSEP\src> julia --project -t4 -- test3.jl
ERROR: LoadError: InvalidStateException: Channel is closed.
Stacktrace:
 [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
   @ Base .\task.jl:871
 [2] wait()
   @ Base .\task.jl:931
 [3] wait(c::Base.GenericCondition{ReentrantLock})
   @ Base .\condition.jl:124
 [4] take_unbuffered(c::Channel{Any})
   @ Base .\channels.jl:433
 [5] take!
   @ .\channels.jl:410 [inlined]
 [6] iterate
   @ C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:25 [inlined]
 [7] outside(t::TestR)
   @ Main C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:41
 [8] top-level scope
   @ C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:46
in expression starting at C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:46