Friendlier output format for dates. Catch errors writing csv. Note that stderr is a function in my code, not an output!
PS C:\Users\rdboylan\Documents\BP\MSEP\src> julia --project -t16 -- bigsim4.jl
0:04.96 (h:mm) remaining in 29 Iterations as of iteration 1 as of 2023-03-31 11:59:08
Finished after 0:00.87 (h:mm) and 30 iterations. Largest std err   2.379 at 2023-03-31 11:59:50.
SystemError: opening file "bigsim4.csv": Permission denied