bigsim4.jl gets new abilities and bugs working toward the production run with new function big4sim -> inconsistent with file name, but consistent with previous naming.
To label some of the NamedArrays this includes a names() function for EVResults.
Also includes nClusters() to compute the recommended number of clusters for an
individual dataset given clusterSize and number of threads.

The problem is that names() throws a seemingly impossible iteration error that the
channel has closed--right after testing for isopen().

In an effort to isolate it I created test3.jl.  But it has no problem.
test3b.jl consisted of direct copies of the code in bigsim4.jl that are relevant.
It errored.

I have already added some complications to test3 to make it more like test3b,
while simplifying test3b.   For the latter:
1. no longer uses anything from MSEP.
2. eliminate reference to member of evr in returned function
3. eliminate returned function entirely (just a constant)
I have also tested and determined the error is not a result of running under VSCode,
nor of using multiple threads.

The error seems deterministic; however, when I run the code under the debugger it
works OK.

Here's the error:
PS C:\Users\rdboylan\Documents\BP\MSEP\src> julia --project -- test3b.jl
ERROR: LoadError: InvalidStateException: Channel is closed.
Stacktrace:
 [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
   @ Base .\task.jl:871
 [2] wait()
   @ Base .\task.jl:931
 [3] wait(c::Base.GenericCondition{ReentrantLock})
   @ Base .\condition.jl:124
 [4] take_unbuffered(c::Channel{Any})
   @ Base .\channels.jl:433
 [5] take!
   @ .\channels.jl:410 [inlined]
 [6] iterate
   @ C:\Users\rdboylan\Documents\BP\MSEP\src\test3b.jl:32 [inlined]
 [7] names(evr::EVRequests)
   @ Main C:\Users\rdboylan\Documents\BP\MSEP\src\test3b.jl:76
 [8] top-level scope
   @ C:\Users\rdboylan\Documents\BP\MSEP\src\test3b.jl:80
in expression starting at C:\Users\rdboylan\Documents\BP\MSEP\src\test3b.jl:80

And for the other file:
PS C:\Users\rdboylan\Documents\BP\MSEP\src> julia --project -- test3.jl
54.598150033144236, 0.36787944117144233, 1.0, 1.7320508075688772,