collect() over iterable.  No help. The failure now moves to the collect invocation, though...
PS C:\Users\rdboylan\Documents\BP\MSEP\src> julia --project -t1 -- test3.jl
ERROR: LoadError: InvalidStateException: Channel is closed.
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base .\task.jl:871
  [2] wait()
    @ Base .\task.jl:931
  [3] wait(c::Base.GenericCondition{ReentrantLock})
    @ Base .\condition.jl:124
  [4] take_unbuffered(c::Channel{Any})
    @ Base .\channels.jl:433
  [5] take!
    @ .\channels.jl:410 [inlined]
  [6] iterate
    @ C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:25 [inlined]
  [7] copyto!(dest::Vector{Any}, src::TestR)
    @ Base .\abstractarray.jl:906
  [8] _collect(cont::UnitRange{Int64}, itr::TestR, #unused#::Base.HasEltype, isz::Base.HasLength)
    @ Base .\array.jl:718
  [9] collect
    @ .\array.jl:712 [inlined]
 [10] outside(t::TestR)
    @ Main C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:39
 [11] top-level scope
    @ C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:50
in expression starting at C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:50