Added some tracing messages. The debugger does not react to breakpoints inside test_helper(), presumably because they execute inside a Task.  Note they are not in a separate thread.
Possibly the order in which the messages are output doesn't match
how they were generated--in particular notice the \n generated
by println("Iterating") does not appear until after the message
that test_helper is exiting.  But it's hard to see how they could be
in any other order to get the errors I'm seeing.

So we enter the iterator twice.  I would expect the channel to be closed
already, and for an immediate return of nothing. Instead the channel
tests as isopen(), but is then discovered to be closed!

PS C:\Users\rdboylan\Documents\BP\MSEP\src> julia --project -t1 -- test3.jl
Iterating.
Iterating.Exiting test_helper.

ERROR: LoadError: InvalidStateException: Channel is closed.
Stacktrace:
 [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
   @ Base .\task.jl:871
 [2] wait()
   @ Base .\task.jl:931
 [3] wait(c::Base.GenericCondition{ReentrantLock})
   @ Base .\condition.jl:124
 [4] take_unbuffered(c::Channel{Any})
   @ Base .\channels.jl:433
 [5] take!
   @ .\channels.jl:410 [inlined]
 [6] iterate
   @ C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:27 [inlined]
 [7] outside(t::TestR)
   @ Main C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:44
 [8] top-level scope
   @ C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:52
in expression starting at C:\Users\rdboylan\Documents\BP\MSEP\src\test3.jl:52