Various small fixes/updates to new scheme.
It now runs until it requires the zhat column, which doesn't exist since
I'm not creating it yet.

PS C:\Users\rdboylan\Documents\BP\MSEP\src> julia --project -t10 -- bigsim4.jl
isDone(1, 1, 1)
isDone(1, 1, 1)
ERROR: LoadError: ArgumentError: column name :zhat not found in the data frame
Stacktrace:
 [1] lookupname
   @ C:\Users\rdboylan\.julia\packages\DataFrames\LteEl\src\other\index.jl:404 [inlined]
 [2] getindex
   @ C:\Users\rdboylan\.julia\packages\DataFrames\LteEl\src\other\index.jl:413 [inlined]
 [3] getindex(df::DataFrames.DataFrame, row_inds::BitVector, col_ind::Symbol)
   @ DataFrames C:\Users\rdboylan\.julia\packages\DataFrames\LteEl\src\dataframe\dataframe.jl:525
 [4] msepabs(r::DataFrames.DataFrame, τ::Float64, col::Symbol)
   @ MSEP C:\Users\rdboylan\Documents\BP\MSEP\src\post.jl:23
 [5] msepabs
   @ C:\Users\rdboylan\Documents\BP\MSEP\src\post.jl:21 [inlined]
 [6] big4sim(evr::EVRequests; μs::Vector{Float64}, σs::Vector{Float64}, τs::Vector{Float64}, clusterSizes::Vector{Int64}, maxsd::Float64)
   @ Main C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:360
 [7] big4sim(evr::EVRequests)
   @ Main C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:334
 [8] top-level scope
   @ C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:383
in expression starting at C:\Users\rdboylan\Documents\BP\MSEP\src\bigsim4.jl:383