Adapt quad_test.jl for latest code and problem.  Results in quad3.jld
Updates for code changes in rest of system
==========================================
1. Y in DataFrame must be BitVector for this code.  Else get
PS C:\Users\rdboylan\Documents\BP\MSEP> date; julia --project -t16  -- src\quad_test.jl

Friday, April 28, 2023 10:30:42 AM
ERROR: LoadError: MethodError: no method matching MSEP.WorkArea(::DataFrame, ::Vector{Bool}, ::LogisticSimpleEvaluator{Float64, typeof(zSQdensity), AgnosticAGK}, ::Vector{QuadGK.Segment{Float64, Float64, Float64}}, ::MSEP.Objective, ::UInt64, ::UInt64, ::UInt64)
Closest candidates are:
  MSEP.WorkArea(::DataFrame, ::BitVector, ::TEvaluator, ::TSegs, ::MSEP.Objective, ::UInt64, ::UInt64, ::UInt64) where {TEvaluator, TSegs} at c:\Users\rdboylan\Documents\BP\MSEP\src\logistic_simple_evaluator.jl:55
  MSEP.WorkArea(::DataFrame, ::TEvaluator) where TEvaluator at c:\Users\rdboylan\Documents\BP\MSEP\src\logistic_simple_evaluator.jl:91
Stacktrace:
 [1] MSEP.WorkArea(dat::DataFrame, ev::LogisticSimpleEvaluator{Float64, typeof(zSQdensity), AgnosticAGK})
   @ MSEP c:\Users\rdboylan\Documents\BP\MSEP\src\logistic_simple_evaluator.jl:93
 [2] quad_test(df::DataFrame; σ::Float64, orders::UnitRange{Int64})
   @ Main C:\Users\rdboylan\Documents\BP\MSEP\src\quad_test.jl:41
 [3] quad3()
   @ Main C:\Users\rdboylan\Documents\BP\MSEP\src\quad_test.jl:104
 [4] top-level scope
   @ C:\Users\rdboylan\Documents\BP\MSEP\src\quad_test.jl:111
in expression starting at C:\Users\rdboylan\Documents\BP\MSEP\src\quad_test.jl:111

Note that it was challenging to get the right syntax to construct the BitVector.
There may well be better alternatives, e.g., falses(n).

2. WorkArea c'tor simplified (old form would probably still work).

Changes for our new problem
===========================
1. Comment out old executable and related code.
2. quad_test() now uses k=-2 instead of -1.  Probably should be an optional arg to function.
3. quad_test() now get zhat() not zsimp().
4. Only clusterSize 20 and sigma=0.5 is of interest.
5. Write results to quad3.jld.
6. Add Serialization module to support 5.

I thought running this would print the final results but it did not.
Here are some results from reading it back in, from email distributed:

We seem to have hit on a uniquely bad combination of parameters.
I evaluated zhat for all successes from 0 through 20 with the order for the adaptive Gauss-Kronrod varying from 3 through 15.
Only a few of these had zhat>10, and our particular problem was much the worst.
I’m just printing the key part of the results with all the problems:
julia> findall(r.>10)
4-element Vector{CartesianIndex{2}}:
CartesianIndex(19, 1)
CartesianIndex(14, 2)
CartesianIndex(14, 4)
CartesianIndex(18, 5)
# The mapping from indices to values makes this awkward
# CartesianIndex(I, j) is for sum Y = i-1 and order = j+2
# So Y=18, order 3
# Y=17, order 7
# Y=13, orders 4 and 6
julia> r[13:21, 1:6]
9×6 Named Matrix{Float64}
Y ╲ order │       3        4        5        6        7        8
──────────┼─────────────────────────────────────────────────────
12        │ 4.10078  4.14317  4.16342   4.1435  4.14323  4.14316
13        │ 1.93542  32.2609  4.50312  40.9685  4.50319  4.27851
14        │ 1.93597     4.87  4.86094     4.87  4.86964  4.86994
15        │ 1.93629  5.24928  5.24928  5.24928  5.24856  5.24916
16        │ 1.94618  5.64738  5.64741  5.64741  5.64741  5.64741
17        │ 3.50018  6.07241   6.0724   6.0724  195.956   6.0724
18        │ 12.0916  6.53473  6.53473  6.53473  6.53473  6.53473
19        │ 7.04874  7.04874  7.04874  7.04874  7.04874  7.04874
20        │ 7.63489  7.63489  7.63489  7.63489  7.63489  7.63489

BTW, there are no estimated zhat < -10.