First cut at zCT.  Needs work. Update dependencies. Also bump dependencies, coincident with move to julia 1.8.5 (was 1.8.2).  Mostly minor bumps, but I couldn't get it to precompile until I did them.
export symbols for CT.
make_zCT_generator creates a CT evaluator om bigbigsim.jl.
CTDensity evaluates density in evaluator.jl.

This takes a long time to run, almost 30m, and some of the answers are nuts.
Really only σ=0.25 has everything looking possible; the rest feature very large
errors with at least some of the individual sum Y predictions being extreme.

Some of the extra time could be the adaptive quadrature trying to cope
with discontinuities, but that alone doesn't explain the bad answers.

Also my last headline is wrong.

Running the last chunk in harness.jl (and a few earlier bits) gives

16

2023-01-15T16:36:30.658

Summary predictors for zCT(λ=2.0, k=-1.0, σ=0.25) AGK(5)
8×5 DataFrame
 Row │ ∑Y      zCT        zCT_sd       zsimp       zsimp_sd
     │ UInt16  Float64    Float64      Float64     Float64
─────┼─────────────────────────────────────────────────────────
   1 │      0  -1.96143   2.64458e-13  -0.438563   3.59161e-14
   2 │      1  -1.1859    3.10036e-12  -0.207592   1.9331e-13
   3 │      2   0.109621  3.08366e-13   0.0229005  4.38673e-14
   4 │      3   1.34382   8.19756e-13   0.252926   1.31205e-13
   5 │      4   2.0302    6.57249e-13   0.482501   1.52363e-13
   6 │      5   2.31794   3.28669e-13   0.711641   3.78945e-14
   7 │      6   2.44182   3.92295e-14   0.940366   1.81038e-14
   8 │      7   2.52559   3.57431e-15   1.16869    1.11697e-15

Summary predictors for zCT(λ=2.0, k=-1.0, σ=0.5) AGK(5)
8×5 DataFrame
 Row │ ∑Y      zCT            zCT_sd       zsimp       zsimp_sd
     │ UInt16  Float64        Float64      Float64     Float64
─────┼─────────────────────────────────────────────────────────────
   1 │      0     -2.36794    1.17019e-12  -0.740417   3.78812e-13
   2 │      1     -1.94696    1.70845e-12  -0.354563   1.97367e-13
   3 │      2     -0.0514021  5.56089e-14   0.0229187  4.13843e-15
   4 │      3  81395.2        1.48328e-7    0.393002   4.87263e-14
   5 │      4      2.32387    2.24322e-13   0.756826   4.96233e-13
   6 │      5      2.43185    4.28609e-13   1.11566    1.09198e-13
   7 │      6      2.5091     1.46199e-13   1.47086    1.20608e-14
   8 │      7      2.60871    1.60082e-14   1.82387    6.00309e-15

Summary predictors for zCT(λ=2.0, k=-1.0, σ=0.75) AGK(5)
8×5 DataFrame
 Row │ ∑Y      zCT       zCT_sd       zsimp       zsimp_sd
     │ UInt16  Float64   Float64      Float64     Float64
─────┼────────────────────────────────────────────────────────
   1 │      0  -2.4033   2.62903e-13  -0.90723    2.68676e-14
   2 │      1  -2.22996  1.80434e-12  -0.43276    8.78357e-13
   3 │      2  -4.98068  1.27522e-11   0.0103556  1.20487e-14
   4 │      3   4.50972  1.98502e-12   0.429355   1.98603e-13
   5 │      4   5.06675  1.76498e-12   0.831709   4.61151e-13
   6 │      5   2.37052  1.73156e-13   1.2248     7.44826e-14
   7 │      6   2.46173  2.82522e-13   1.6159     1.31904e-13
   8 │      7   2.5911   2.88756e-14   2.0122     4.17585e-14

Summary predictors for zCT(λ=2.0, k=-1.0, σ=1.0) AGK(5)
8×5 DataFrame
 Row │ ∑Y      zCT         zCT_sd       zsimp        zsimp_sd
     │ UInt16  Float64     Float64      Float64      Float64
─────┼───────────────────────────────────────────────────────────
   1 │      0  -2.39588    3.49634e-12  -0.990838    8.41222e-13
   2 │      1  -2.29863    3.91378e-12  -0.463378    9.27969e-13
   3 │      2  -5.06453    6.62496e-12  -0.00221081  3.07295e-15
   4 │      3   3.66647    2.4974e-12    0.415056    2.40733e-13
   5 │      4   5.06698    3.11356e-12   0.80766     1.34352e-13
   6 │      5   3.71832e5  1.22438e-7    1.19234     3.9751e-13
   7 │      6   2.39559    3.25974e-13   1.58494     1.17308e-13
   8 │      7   2.53656    1.34576e-13   2.00221     1.4035e-13

Summary predictors for zCT(λ=2.0, k=-1.0, σ=1.25) AGK(5)
8×5 DataFrame
 Row │ ∑Y      zCT         zCT_sd       zsimp       zsimp_sd
     │ UInt16  Float64     Float64      Float64     Float64
─────┼──────────────────────────────────────────────────────────
   1 │      0  -2.38845    2.46649e-12  -1.02971    1.46151e-12
   2 │      1  -1.99648e5  1.6788e-7    -0.466916   5.41285e-13
   3 │      2  -5.06698    4.95556e-12  -0.0110569  7.30887e-15
   4 │      3   1.56157    1.69554e-12   0.383628   2.33103e-13
   5 │      4   5.06702    2.00365e-12   0.749578   2.43027e-13
   6 │      5   5.06704    2.28824e-12   1.11218    7.82054e-13
   7 │      6   2.3388     3.02501e-13   1.49597    3.7038e-13
   8 │      7   2.4847     2.03405e-13   1.93076    2.59586e-13

1648.040723 seconds (115.52 G allocations: 1.694 TiB, 53.45% gc time, 0.75% compilation time: 13% of which was recompilation)

zCT (λ = 2.0) MSEP to I(|z|>τ)

ERROR: UndefVarError: errsAB not defined
Stacktrace:
 [1] top-level scope
   @ c:\Users\rdboylan\Documents\BP\MSEP\src\harness.jl:97

5×4 Named Matrix{Float64}
σ ╲ τ │       -Inf         1.5         2.0         2.5
──────┼───────────────────────────────────────────────
0.25  │    1.94105     3.02136     3.75517     4.76979
0.5   │  1.23474e9   1.02384e9   8.62437e8   6.83479e8
0.75  │    12.5117     5.01904     2.64302     1.37686
1.0   │  8.91281e9  2.04097e10  1.89155e10  1.37426e10
1.25  │  8.74407e9   3.82851e9   2.45942e9   1.53608e9

zBP MSEP for I(|z|>τ)

5×4 Named Matrix{Float64}
σ ╲ τ │     -Inf       1.5       2.0       2.5
──────┼───────────────────────────────────────
0.25  │ 0.924226   3.38847   4.95733   6.95073
0.5   │ 0.749531       2.4   3.44625    4.8143
0.75  │ 0.582908   1.62155   2.37223   3.41664
1.0   │ 0.458404   1.16088   1.79681   2.75556
1.25  │ 0.373778  0.922958   1.51522   2.46149

julia>