Modification to get lines working properly.  Distributed result. Slightly Different values since random.
16

2022-10-31T18:01:19.636

Summary predictors for σ =0.25
7×5 DataFrame
 Row │ ∑Y      zSQ         zSQ_sd       zsimp       zsimp_sd
     │ UInt16  Float64     Float64      Float64     Float64
─────┼──────────────────────────────────────────────────────────
   1 │      0  -1.76666    7.12003e-15  -0.438563   1.61313e-15
   2 │      1  -0.846583   6.93244e-15  -0.207592   1.95002e-15
   3 │      2   0.0457445  1.48092e-16   0.0229005  2.22792e-16
   4 │      3   0.914282   4.35703e-15   0.252926   1.42192e-15
   5 │      4   1.76357    9.53296e-16   0.482501   1.22102e-15
   6 │      5   2.59856    1.03539e-15   0.711641   2.2974e-16
   7 │      6   3.42445    5.1279e-16    0.940366   0.0

Summary predictors for σ =0.5
8×5 DataFrame
 Row │ ∑Y      zSQ         zSQ_sd       zsimp       zsimp_sd
     │ UInt16  Float64     Float64      Float64     Float64
─────┼──────────────────────────────────────────────────────────
   1 │      0  -2.26547    0.0          -0.740417   1.7793e-15
   2 │      1  -1.04528    9.97243e-15  -0.354563   1.03069e-15
   3 │      2  -0.0153731  1.23636e-16   0.0229187  1.68053e-16
   4 │      3   0.897033   7.38938e-15   0.393002   1.90498e-16
   5 │      4   1.74902    4.45321e-16   0.756826   9.73127e-16
   6 │      5   2.58768    2.92167e-16   1.11566    4.03273e-16
   7 │      6   3.45779    3.31005e-16   1.47086    5.38836e-16
   8 │      7   4.40954    0.0           1.82387    0.0

Summary predictors for σ =0.75
8×5 DataFrame
 Row │ ∑Y      zSQ         zSQ_sd       zsimp       zsimp_sd
     │ UInt16  Float64     Float64      Float64     Float64
─────┼──────────────────────────────────────────────────────────
   1 │      0  -2.34377    1.06744e-14  -0.90723    2.77979e-15
   2 │      1  -0.993942   5.90598e-15  -0.43276    5.22574e-15
   3 │      2  -0.0418906  4.79787e-17   0.0103556  7.08281e-17
   4 │      3   0.729599   8.19612e-16   0.429355   1.53452e-15
   5 │      4   1.43402    7.75266e-16   0.831709   1.61514e-16
   6 │      5   2.14915    2.6045e-15    1.2248     3.24726e-15
   7 │      6   2.95821    9.72951e-16   1.6159     2.25715e-16
   8 │      7   3.99588    0.0           2.0122     0.0

Summary predictors for σ =1.0
8×5 DataFrame
 Row │ ∑Y      zSQ         zSQ_sd       zsimp        zsimp_sd
     │ UInt16  Float64     Float64      Float64      Float64
─────┼───────────────────────────────────────────────────────────
   1 │      0  -2.32201    1.7787e-15   -0.990838    8.67116e-15
   2 │      1  -0.892384   4.55661e-15  -0.463378    4.43029e-15
   3 │      2  -0.0475961  1.77076e-16  -0.00221081  2.36641e-17
   4 │      3   0.593401   1.10473e-16   0.415056    1.18899e-15
   5 │      4   1.17266    1.55763e-15   0.80766     2.14027e-15
   6 │      5   1.77711    4.88402e-16   1.19234     2.64677e-15
   7 │      6   2.5149     8.22531e-16   1.58494     2.20249e-15
   8 │      7   3.63323    1.80672e-15   2.00221     0.0

Summary predictors for σ =1.25
8×5 DataFrame
 Row │ ∑Y      zSQ        zSQ_sd       zsimp       zsimp_sd
     │ UInt16  Float64    Float64      Float64     Float64
─────┼─────────────────────────────────────────────────────────
   1 │      0  -2.27838   2.17865e-14  -1.02971    1.33387e-15
   2 │      1  -0.792358  5.11256e-15  -0.466916   2.84549e-15
   3 │      2  -0.04628   9.38746e-17  -0.0110569  4.77134e-17
   4 │      3   0.494167  1.35442e-16   0.383628   2.85204e-15
   5 │      4   0.979923  3.2219e-16    0.749578   6.87878e-17
   6 │      5   1.49682   5.08004e-16   1.11218    2.89948e-15
   7 │      6   2.16567   4.46927e-16   1.49597    2.4581e-15
   8 │      7   3.35486   3.14018e-15   1.93076    1.57009e-15

zSQ (λ =0.4) MSEP for |z|>τ

5×4 Named Matrix{Float64}
σ ╲ τ │     -1.0       1.5       2.0       2.5
──────┼───────────────────────────────────────
0.25  │   1.4948   2.70048   3.52588   5.00346
0.5   │  1.41881   1.45745    1.6259   1.47828
0.75  │   1.1587   1.00105  0.964777   1.67385
1.0   │ 0.988421  0.743334  0.632624  0.570634
1.25  │ 0.798414  0.651015  0.560793  0.403272

zBP MSEP for |z|>τ

5×4 Named Matrix{Float64}
σ ╲ τ │     -1.0       1.5       2.0       2.5
──────┼───────────────────────────────────────
0.25  │ 0.916927    3.2716   4.94026   7.08173
0.5   │ 0.752421   2.25513   3.18358   4.53262
0.75  │ 0.574436   1.64571   2.21068   3.41251
1.0   │ 0.476574   1.14994    1.7136   2.24065
1.25  │ 0.346319  0.856368   1.35464   2.09758

5-element Vector{Float64}:
 0.25
 0.5
 0.75
 1.0
 1.25

40×4 DataFrame
 Row │ pred    σ        τ        MSEP
     │ String  Float64  Float64  Float64
─────┼────────────────────────────────────
   1 │ zSQ        0.25     -1.0  1.4948
   2 │ zSQ        0.5      -1.0  1.41881
   3 │ zSQ        0.75     -1.0  1.1587
   4 │ zSQ        1.0      -1.0  0.988421
  ⋮  │   ⋮        ⋮        ⋮        ⋮
  38 │ zBP        0.75      2.5  3.41251
  39 │ zBP        1.0       2.5  2.24065
  40 │ zBP        1.25      2.5  2.09758
                           33 rows omitted

ERROR: MethodError: no method matching +(::Plot, ::Gadfly.Geom.LineGeometry)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:591
  +(::ChainRulesCore.Tangent{P}, ::P) where P at C:\Users\rdboylan\.julia\packages\ChainRulesCore\C73ay\src\tangent_arithmetic.jl:146
  +(::ChainRulesCore.AbstractThunk, ::Any) at C:\Users\rdboylan\.julia\packages\ChainRulesCore\C73ay\src\tangent_arithmetic.jl:122
  ...
Stacktrace:
 [1] top-level scope
   @ c:\Users\rdboylan\Documents\BP\MSEP\src\harness.jl:68

julia>